### PR TITLE
Fix grpc transcoding bugs for unknown fields

### LINKED ISSUE #795: gRPC transcoder may truncate response data for unknown proto fields
If a proto field is unknown to ESP,  the transcoded response data maybe truncated.  This could happen when proto files used by ESP (the proto descriptor file used in "gcloud endpoints service deploy") and gRPC server are not in sync.

Example 1. a new field is recently added, but gRPC server is using updated proto, but ESP is using the old one. 
Example 2: a removed field, gRPC server is using old proto with that field, but ESP is using new proto.

This is because ESP did not implement Skip() [function](https://github.com/cloudendpoints/esp/blob/master/src/grpc/zero_copy_stream.h#L57).

Please see details [discussion](https://groups.google.com/d/msgid/google-cloud-endpoints/f5d681bc-6d2d-4eba-b02a-e9119d8b70d0%40googlegroups.com?utm_medium=email&utm_source=footer).

### PR DESCRIPTION
**Pull request by qiwzhang**
Signed-off-by: Wayne Zhang <qiwzhang@google.com>

Fixes #795.

It is based on https://github.com/cloudendpoints/esp/pull/796

### CODE REVIEW

**Comment by qiwzhang** [comment]
@bnordli

Please review this change

**Comment by bnordli** [comment]
LGTM!

**Comment by qiwzhang** [comment]
pre-e2e test passed:
https://endpoints-jenkins.appspot.com/me/my-views/view/All/job/jenkins-testing/job/pr-e2e/290/

File: src/grpc/zero_copy_stream.cc [hunk 1]
```diff
@@ -65,9 +68,40 @@ bool GrpcZeroCopyInputStream::Next(const void** data, int* size) {
...
+    }
+  }
+
+  // Move the position ahead the requested number of bytes.
+  position_ += count_left;
+  bytes_read_ += count_left;
+  return true;
+}
+
+::google::protobuf::int64 GrpcZeroCopyInputStream::ByteCount() const {
```
Comment (nareddyt) [inline src/grpc/zero_copy_stream.cc:101]: Thanks for implementing this too. Just curious, do you know where this used/needed? I'm assuming it's not related to originally reported error.

Comment (nareddyt) [reply src/grpc/zero_copy_stream.cc:101]: Oh, I see it's part of the contract for `Skip`.

```
  // Skips a number of bytes.  Returns false if the end of the stream is
  // reached or some input error occurred.  In the end-of-stream case, the
  // stream is advanced to the end of the stream (so ByteCount() will return
  // the total size of the stream).
  virtual bool Skip(int count) = 0;

  // Returns the total number of bytes read since this object was created.
  virtual int64_t ByteCount() const = 0;
```

File: src/grpc/zero_copy_stream_test.cc [hunk 2]
```diff
@@ -166,68 +176,206 @@ TEST_F(GrpcZeroCopyInputStreamTest, Backups) {
...
+  EXPECT_TRUE(stream.Next(&data, &size));
+  EXPECT_EQ(slice2.size(), size);
   EXPECT_EQ(slice2, std::string(reinterpret_cast<const char *>(data), size));
 
   // Back up and test again
   stream.BackUp(size);
   EXPECT_EQ(slice2.size(), stream.BytesAvailable());
-  ASSERT_TRUE(stream.Next(&data, &size));
-  ASSERT_EQ(slice2.size(), size);
+  EXPECT_EQ(5 + slice1.size(), stream.ByteCount());
```
Comment (nareddyt) [inline src/grpc/zero_copy_stream_test.cc:228]: Are you sure `ByteCount` should double count the bytes after a back up? I didn't find any documentation on this.

File: src/grpc/zero_copy_stream_test.cc [hunk 3]
```diff
@@ -166,68 +176,206 @@ TEST_F(GrpcZeroCopyInputStreamTest, Backups) {
...
+  EXPECT_TRUE(stream.Next(&data, &size));
+  EXPECT_EQ(slice2.size() - 1, size);
   EXPECT_EQ(slice2.substr(1),
             std::string(reinterpret_cast<const char *>(data), size));
 
   // Check the end of the stream
   EXPECT_FALSE(stream.Next(&data, &size));
 }
 
+TEST_F(GrpcZeroCopyInputStreamTest, Skips) {
```
Comment (nareddyt) [inline src/grpc/zero_copy_stream_test.cc:246]: So this is just testing the the `Skip` functionality works correctly (and with the other CodedInputStream functions). Is there any easy way to test the original error reported in #795, using unknown fields? A regression test would be nice

File: src/grpc/zero_copy_stream.cc [hunk 4]
```diff
@@ -65,9 +68,40 @@ bool GrpcZeroCopyInputStream::Next(const void** data, int* size) {
...
+    // Safe guard against wrong usage.
+    return false;
+  }
+  size_t count_left = static_cast<size_t>(count);
+  while (position_ + count_left > current_buffer_size_) {
+    // Skipping past the current buffer, read the next one.
+    int delta = static_cast<int>(current_buffer_size_ - position_);
+    count_left -= delta;
+    bytes_read_ += delta;
+    position_ = 0;
```
Comment (nareddyt) [inline src/grpc/zero_copy_stream.cc:86]: Are you sure setting the position to 0? I assumed `Next` should be called from the caller function.

```
In the end-of-stream case, the stream is advanced to the end of the stream.
```

Comment (qiwzhang) [reply src/grpc/zero_copy_stream.cc:86]: serrialize_.Next() will set current_bufer_size_ to 0,   with position_=0. it is end of the stream.   What is the problem?

File: src/grpc/zero_copy_stream.cc (hunk 1 above)
Comment (qiwzhang) [reply src/grpc/zero_copy_stream.cc:101]: Ack

File: src/grpc/zero_copy_stream_test.cc (hunk 2 above)
Comment (qiwzhang) [reply src/grpc/zero_copy_stream_test.cc:228]: ByteCount() should not double count,  it should be the count from start of stream to current position.

File: src/grpc/zero_copy_stream_test.cc (hunk 3 above)
Comment (qiwzhang) [reply src/grpc/zero_copy_stream_test.cc:246]: We can write a t test for the original reported problem.

File: src/grpc/zero_copy_stream.cc (hunk 4 above)
Comment (nareddyt) [reply src/grpc/zero_copy_stream.cc:86]: Ack, I understand now.

File: src/grpc/zero_copy_stream_test.cc (hunk 3 above)
Comment (qiwzhang) [reply src/grpc/zero_copy_stream_test.cc:246]: Added a t test

File: test/transcoding/service.pb.txt [hunk 5]
```diff
@@ -481,6 +486,27 @@ types {
   }
   syntax: SYNTAX_PROTO3
 }
+types {
+  name: "endpoints.examples.bookstore.UnknownBook"
+  fields {
```
Comment (qiwzhang) [inline test/transcoding/service.pb.txt:491]: FYI,  I manually deleted "unknown" field and "UknownMsg" from the service config.

File: src/nginx/t/transcoding_ignore_unknown_fields.t [hunk 6]
```diff
@@ -103,6 +103,18 @@ EOF
 ok(ApiManager::verify_http_json_response($response,
     {'id'=>'100', 'theme' => 'Classics'}), "The shelf was created successfully.");
 
+# Test unknown field in response. ResponseMessage UnknownBook has a field "unknown"
+# which is known to gRPC server, but not to ESP.
+# Expected result is: only that field is skipped, other fields should be fine.
+my $response1 = ApiManager::http_get($NginxPort,'/unknownbook?key=this-is-an-api-key');
+
+# With bug in https://github.com/cloudendpoints/esp/issues/795, the first field
+# after the uknown is discarded. Once the bug is fixed, use follow correct result.
```
Comment (qiwzhang) [inline src/nginx/t/transcoding_ignore_unknown_fields.t]: Without the fix,  the first field "known_int" is discarded.  With the fix,  all fields are there

File: src/grpc/zero_copy_stream_test.cc [hunk 7]
```diff
@@ -166,68 +176,206 @@ TEST_F(GrpcZeroCopyInputStreamTest, Backups) {
...
+  GrpcZeroCopyInputStream stream;
+
+  // Create and add a message
+  std::string slice1 = "This is the first slice of the message.";
+  std::string slice2 = "This is the second slice of the message.";
+  std::string slice3 = "This is the third slice of the message.";
+  std::string slice4 = "This is the fourth slice of the message.";
+  const int kFrameSize = 5;
```
Comment (TAOXUY) [inline src/grpc/zero_copy_stream_test.cc:254]: Overall LGTM
Is it possible to put them into a test fixture and make the rest tests into several tests? It is hard to read while you need to keep a large context.

Comment (TAOXUY) [inline src/grpc/zero_copy_stream_test.cc:254]: Comment `The size of message delimiter`?

Comment (qiwzhang) [reply src/grpc/zero_copy_stream_test.cc:254]: This test is very stateful test; each test step depends on its position.  Even splitting into multiple test cases, each case still needs to move into that position in order to test that specific case, it will not help much for readability.

Comment (qiwzhang) [reply src/grpc/zero_copy_stream_test.cc:254]: grpc frame size is 5.

Comment (qiwzhang) [reply src/grpc/zero_copy_stream_test.cc]: Replace all hard coded "5" with kFrameSize and add comment for kFrameSize

Comment (qiwzhang) [reply src/grpc/zero_copy_stream_test.cc]: Step sequencing is important in such tests, Backup, and Skip.  By splitting the test, the sequencing will be changed, will be simpler,  it will be different tests.  For now, I decided not to change it.
